# Scraping TranfertMarket

## Prerequisites

### Import required Libraries

In [40]:
from selenium import webdriver 
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import requests
from lxml import html
from bs4 import BeautifulSoup
import re

### Creating DataFrames

In [59]:
# Initialize empty DataFrame
PlayersTM = pd.DataFrame(columns=['Player_Name', 'Market_Value'])
    
    # Headers to mimic a real browser request
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

## Scraping phase

### Setting up league URLs

In [42]:
# defining TOP5 Leagues url variable
PLurl = "https://www.transfermarkt.fr/premier-league/startseite/wettbewerb/GB1"
Ligaurl = "https://www.transfermarkt.fr/laliga/startseite/wettbewerb/ES1"
Bundesligaurl = "https://www.transfermarkt.fr/bundesliga/startseite/wettbewerb/L1"
SerieAurl = "https://www.transfermarkt.fr/serie-a/startseite/wettbewerb/IT1"
Ligue1url = "https://www.transfermarkt.fr/ligue-1/startseite/wettbewerb/FR1"

#defining path variable for the ChromeDriver
brave_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"

### Let's create a function to scrape team links from league pages

In [43]:
#create a function to colllecte teams website links

Links_list = []
def get_url(url):
    # Configure Brave path
 # UPDATE THIS

    # Set WebDriver options for Brave
    options = Options()
    options.binary_location = brave_path 
    # Initialize the driver (use ChromeDriver)
    driver = webdriver.Chrome(service=Service(), options=options)
    driver.get(url)

    # define a container to hold the teams table 
    container = driver.find_element(By.XPATH, '//*[@id="yw1"]/table/tbody')

    # search for team links within the container
    team_links = container.find_elements(By.TAG_NAME, 'a')
    team_urls = [link.get_attribute('href') for link in team_links]

    # adding the team URLs to the Links_list if they are not already present
    for link in team_urls:
        if link not in Links_list:
            Links_list.append(link)
    
    # close the driver
    driver.quit()
    return None

### Now let's apply our function to collect team links from the top 5 European leagues

In [44]:
get_url(PLurl)
get_url(Ligaurl)    
get_url(Bundesligaurl)
get_url(SerieAurl)
get_url(Ligue1url)

### Remove Duplicates

In [45]:
# we see that theres duplicates for all teams and some useless links (e.g. league links) so we will remove them
Links_list.pop(1)
Links_list.pop(41)
Links_list.pop(83)
Links_list.pop(118)
Links_list.pop(157)               
Links = []
# Remove duplicates
for i in range(len(Links_list)):
    if i % 2 == 0 and Links_list[i] not in Links:
        Links.append(Links_list[i])

### Check the number of teams

In [46]:
len(Links)

96

### Scraping function

In [58]:
scraped_links = []

In [60]:
def scrape_team_players(team_url, df = PlayersTM):
    global PlayersTM
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    response = requests.get(team_url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Find squad table
    squad_table = soup.find('table', class_='items')
    player_rows = squad_table.find_all('tr', class_=['odd', 'even'])
    
    for row in player_rows:
        # Get player name
        name_cell = row.find('td', class_='hauptlink')
        player_name = name_cell.find('a').text.strip()
        
        # Get market value
        value_cell = row.find('td', class_='rechts hauptlink')
        market_value = value_cell.text.strip()
    
        
        # Add to DataFrame
        new_row = pd.DataFrame({
            'Player_Name': [player_name],
            'Market_Value': [market_value],
        })
        
        PlayersTM = pd.concat([PlayersTM, new_row], ignore_index=True)
        scraped_links.append(team_url)
    return PlayersTM

### Lets test the function

In [61]:
scrape_team_players("https://www.transfermarkt.fr/manchester-city/startseite/verein/281")

            Player_Name   Market_Value
0               Ederson   20,00 mio. €
1         Stefan Ortega    8,00 mio. €
2     Marcus Bettinelli        600 K €
3            Rúben Dias   65,00 mio. €
4    Abdukodir Khusanov   35,00 mio. €
5            Vitor Reis   30,00 mio. €
6         Manuel Akanji   28,00 mio. €
7           John Stones   25,00 mio. €
8            Nathan Aké   25,00 mio. €
9        Josko Gvardiol   75,00 mio. €
10      Rayan Aït-Nouri   35,00 mio. €
11  Josh Wilson-Esbrand    4,00 mio. €
12           Rico Lewis   40,00 mio. €
13          Issa Kaboré    4,00 mio. €
14                Rodri  110,00 mio. €
15      Kalvin Phillips   12,00 mio. €
16    Tijjani Reijnders   60,00 mio. €
17        Nico González   40,00 mio. €
18        Matheus Nunes   35,00 mio. €
19        Mateo Kovacic   20,00 mio. €
20         Sverre Nypan   15,00 mio. €
21       İlkay Gündoğan    5,00 mio. €
22       Bernardo Silva   38,00 mio. €
23         James McAtee   20,00 mio. €
24    Claudio Echeverri   18,00 mio. €
25        Nico O'Reilly   18,00 mio. €
26          Jérémy Doku   50,00 mio. €
27        Jack Grealish   28,00 mio. €
28           Phil Foden  100,00 mio. €
29              Savinho   50,00 mio. €
30         Rayan Cherki   45,00 mio. €
31           Oscar Bobb   25,00 mio. €
32       Erling Haaland  180,00 mio. €
33        Omar Marmoush   75,00 mio. €

In [86]:
for link in Links:
    if link in scraped_links:
        continue
    try :
        scrape_team_players(link)
    except Exception as e:
        continue

In [89]:
# check which links were not scraped
not_scraped=[link for link in Links if link not in scraped_links]
len(not_scraped)

3

In [88]:
# treat not scraped links as errors
for link in not_scraped:
    try:
        scrape_team_players(link)
    except Exception as e:
        print(f"Error while scraping {link}: {e}")
        continue

Error while scraping https://www.transfermarkt.fr/premier-league/startseite/wettbewerb/GB1#: 'NoneType' object has no attribute 'text'
Error while scraping https://www.transfermarkt.fr/serie-a/startseite/wettbewerb/IT1#: 'NoneType' object has no attribute 'find_all'
Error while scraping https://www.transfermarkt.fr/fc-paris-saint-germain/startseite/verein/583/saison_id/2025: 'NoneType' object has no attribute 'find_all'

### the first two links is a league page link, and the third for PSG, so we gonna scrape psg individually

In [90]:
scrape_team_players("https://www.transfermarkt.fr/paris-saint-germain/startseite/verein/583")

             Player_Name  Market_Value
0                Ederson  20,00 mio. €
1          Stefan Ortega   8,00 mio. €
2      Marcus Bettinelli       600 K €
3             Rúben Dias  65,00 mio. €
4     Abdukodir Khusanov  35,00 mio. €
...                  ...           ...
2744         Désiré Doué  90,00 mio. €
2745         Kang-in Lee  25,00 mio. €
2746       Ibrahim Mbaye   3,00 mio. €
2747       Gonçalo Ramos  40,00 mio. €
2748   Randal Kolo Muani  30,00 mio. €

[2749 rows x 2 columns]

### Final dataframes from TM

In [91]:
PlayersTM

             Player_Name  Market_Value
0                Ederson  20,00 mio. €
1          Stefan Ortega   8,00 mio. €
2      Marcus Bettinelli       600 K €
3             Rúben Dias  65,00 mio. €
4     Abdukodir Khusanov  35,00 mio. €
...                  ...           ...
2744         Désiré Doué  90,00 mio. €
2745         Kang-in Lee  25,00 mio. €
2746       Ibrahim Mbaye   3,00 mio. €
2747       Gonçalo Ramos  40,00 mio. €
2748   Randal Kolo Muani  30,00 mio. €

[2749 rows x 2 columns]

In [92]:
# Save the DataFrame to a CSV file
PlayersTM.to_csv('PlayersTM.csv', index=False)